#!/bin/bash


#################################################################


#set the directory from where wallpapers are to be choosed 
directory="$HOME/.config/wallee"

#set the time interval for transition of wallpaper in minutes
time=2

cd $director

while true
	do
		for f in $directory/*
			do
		
				`exec feh --bg-fill "$f"`
		
				sleep $[ $time*60 ]
			done
	done


###################################################################
