#!/bin/bash


#################################################################


#set the directory from where wallpapers are to be choosed 
DIR="$HOME/.config/wallee"

#set the time interval for transition of wallpaper in minutes
TIME=2

cd $director

while true
	do
		for f in $DIR/*
			do
		
				`exec feh --bg-fill "$f"`
		
				sleep $[ $TIME*60 ]
			done
	done


###################################################################
